## Altair (Vega-Altair)

Now we will be using a module in python called [Altair](https://altair-viz.github.io/index.html) which provides various functions to actually perform plots for us. There are lots of other modules in python that do similar things, all with various pros and cons. Altair is used here because it produces good looking and readable visualisations, but it is flexible and friendly API after spending some time. 

`Declarative visualization means that you need to think about data and relationships, instead incidental details`

- There is lots of information on Altair on the web pages describing it https://altair-viz.github.io/index.html. 
- The 'getting started' pages are a good quick read to get a sense of how data visualisations are expressed in Altait https://altair-viz.github.io/getting_started/starting.html.
- These are a great source of reference and something we will come back to throughout discussing python data visualisations in the course. 

That looks similar to the grammer of graphics if you are familiar with the ggplot world for R users, we are adding all those data viz grammatical pieces one by one to create our visualizatio. This video can be a good supplementary on the [Altair's Visualization Grammer](https://www.youtube.com/watch?v=U7w1XumKK60) if you would like to watch later.  

<img src="Altair_layers.png" width="500" height="2000">

A good place to start is to look at the gallery of example visualisations https://altair-viz.github.io/gallery/index.html. 

This link provides lots of exemplars of the sorts of things that can be done using Altair. A very basic way to get started with producing a new visualisation is to find the closest gallery example to the thing you wish to produce and then cut and paste the example code used to make it as a starting point, after creating a sketch that you are imagining. 

If you are novice learners, for the portfolio assignment, it might be better to focus on seaborn and plotnine examples first. After dealing with these examples, you can check out the altair in detail, especially for the interactivity. On that other hand, for the interactive plots, you are free to go with other tools in your final project if you need it.

## Main steps of Altair 

1. **Import Libraries**: Import necessary libraries such as Altair and Pandas to handle data and create visualizations.
   
2. **Prepare Your Data**: Load and prepare your data using Pandas, ensuring it's in a suitable format for visualization.
   
3. **Create a Base Chart**: Use `alt.Chart()` to define a base chart with your DataFrame as the starting point.
   
4. **Choose a Mark Type**: Select the type of visualization (e.g., bar, line, scatter) using the appropriate `mark_*` method.
   
5. **Encode Data**: Map data fields to visual properties like axes, colors, and sizes using the `encode()` method.
   
6. **Display the Chart**: Render the chart in a Jupyter Notebook or save it to a file for sharing or further analysis.

Similar to three main layers in plotnine, we have similar setting in altair environment. Besides, the core concepts required to create a basic Altair chart can be summarized below:

- **Data, Marks, and Encodings**: the three core pieces of an Altair chart
- **Encoding Types**: Q (quantitative), N (nominal), O (ordinal), T (temporal), which drive the visual representation of the encodings
- **Binning and Aggregation**: which let you control aspects of the data representation within Altair.

As a starting data example, good to look at that these steps in cars data set, from here with simple charts on a different data; [Simple Charts: core concepts](https://altair-viz.github.io/altair-tutorial/notebooks/02-Simple-Charts.html)


### About Marks 

Remember that the essential elements of an Altair chart are the data, the mark, and the encoding. There are a number of available marks that you can use;

| Mark      | Method          | Description                                      |
|-----------|----------------|--------------------------------------------------|
| Arc       | `mark_arc()`    | A pie chart.                                    |
| Area      | `mark_area()`   | A filled area plot.                             |
| Bar       | `mark_bar()`    | A bar plot.                                     |
| Circle    | `mark_circle()` | A scatter plot with filled circles.            |
| Geoshape  | `mark_geoshape()` | Visualization containing spatial data.      |
| Image     | `mark_image()`  | A scatter plot with image markers.             |
| Line      | `mark_line()`   | A line plot.                                    |
| Point     | `mark_point()`  | A scatter plot with configurable point shapes. |
| Rect      | `mark_rect()`   | A filled rectangle, used for heatmaps.         |
| Rule      | `mark_rule()`   | A vertical or horizontal line spanning the axis. |
| Square    | `mark_square()` | A scatter plot with filled squares.            |
| Text      | `mark_text()`   | A scatter plot with points represented by text. |
| Tick      | `mark_tick()`   | A vertical or horizontal tick mark.            |
| Trail     | `mark_trail()`  | A line with variable widths.                    |

### Data Types

The basic data types supported by Altair are as follows:

| Data Type     | Shorthand Code | Description                          |
|---------------|--------------|--------------------------------------|
| **quantitative** | 'Q'          | A continuous real-valued quantity   |
| **ordinal**      | 'O'          | A discrete ordered quantity         |
| **nominal**      | 'N'          | A discrete unordered category       |
| **temporal**     | 'T'          | A time or date value                |
| **geojson**      | 'G'          | A geographic shape                  |

### About Encodings

The next step is to add visual encoding channels to the selected chart. An encoding channel specifies how a given data column should be mapped onto the visual properties of the visualization. Some of the more frequenty used visual encodings are listed here:

| Channel   | Altair Class | Description                         |
|-----------|-------------|-------------------------------------|
| x         | `X`         | The x-axis value                   | 
| y         | `Y`         | The y-axis value                   | 
| x2        | `X2`        | Second x value for ranges          | 
| y2        | `Y2`        | Second y value for ranges          | 
| longitude | `Longitude` | Longitude for geo charts           |
| latitude  | `Latitude`  | Latitude for geo charts            | 
| color    | `Color`     | Color of the mark                    |
| opacity  | `Opacity`   | Transparency/opacity of the mark     |
| shape    | `Shape`     | Shape of the mark                    |
| size     | `Size`      | Size of the mark                     |
| row      | `Row`       | Row within a grid of facet plots     |
| column   | `Column`    | Column within a grid of facet plots  |

### Simple visualisations with Altair

First let's look at visualising some data with lines, points, area, bar charts and bubbles. 

- The basic data model used by Altair is tabular data, similar to a spreadsheet or database table.
- When data is specified as a pandas DataFrame, Altair uses the data type information provided by pandas to automatically determine the data types required in the encoding

We can use some data about US fish imports (value in US dollars) over recent years. This comes from open data from the US government:
https://www.ers.usda.gov/data-products/aquaculture-data.aspx

This has a combination of quantitative variables (import value in dollars each year), and qualitative variables (year, product).

In [1]:
# First we do some module imports:
import pandas as pd
import altair as alt

In [2]:
fish = pd.read_excel('fishimportdata.xlsx')
fish.head()

,Product,2014,2015,2016,2017,2018
0,"Trout, fresh and frozen",95011.936,104791.429,120977.955,135236.725,164695.746
1,"Atlantic salmon, fresh",568901.674,658831.066,842603.917,948877.175,1035924.073
2,"Pacific salmon, fresh",111540.545,69978.873,80010.180,70733.165,90324.372
3,"Atlantic salmon, frozen",21457.836,16356.453,24230.787,22492.341,20197.169
4,"Pacific salmon, frozen",224334.704,238962.677,246204.469,302340.719,360673.107

### Lines, points, areas

Starting with a line, Altair asks us to specify the data for a 'Chart' (visualisation) that we make, and then what mark we use (in this case a line), and what we want to encode (for a line this needs an x and y axis).

Putting that all together as simply as we can it looks as follows:

In [10]:
# This code creates a line chart using the fish DataFrame. The mark_line() function specifies
# that the chart should be a line plot. The encode() method maps the 'Product' column to the
# x-axis and the '2014' column to the y-axis, plotting the 2014 values for each product.

alt.Chart(fish).mark_line().encode(
    x='Product',
    y='2014')

alt.Chart(...)

In [12]:
# Or we can look at a bar chart for the specific year similarly 
alt.Chart(fish).mark_bar().encode(
    x='Product',
    y='2014')

alt.Chart(...)

In [7]:
alt.Chart(fish).mark_bar()

alt.Chart(...)

- You can see Altair provides all the parts that we want to use to make up our plot as functions that we can call using the . (dot) notation to specify a function within the module, or within the chart we set up.

In [13]:
# This code creates a scatter plot with circular markers using the fish DataFrame. The mark_circle(size=80)
# function specifies that the markers should be circles with a size of 80. The x-axis represents 'Product',
# and the y-axis represents the values from 2014.
alt.Chart(fish).mark_circle(size=80).encode(
    x='Product',
    y='2014'
)

alt.Chart(...)

Note we have also introduced something new - we added an option to the mark function of our plot that marked on the circles for our data - size=80, this is an option to choose the size of the mark (circles in this case) used.  
Let's suppose we didn't like circles - we can change to a different type of 'point' marker, and show some more options while we are at it:

In [14]:
# This code generates a scatter plot with square markers using the fish DataFrame. The mark_point() function
# is used with additional parameters to set the shape to 'square' and the color to 'red'. The size of the
# markers is set to 80. The plot maps 'Product' to the x-axis and '2014' to the y-axis.
alt.Chart(fish).mark_point(size=80, shape='square', color='red').encode(
    x='Product',
    y='2014',
)

alt.Chart(...)

**Try followings and reflect on**

- Modify the `shape='square'` to another shape, such as 'circle' or 'triangle'. What happens? How does the visualization change? 
- Change `.mark_point()` to `.mark_bar()`. Does it work as expected? What adjustments are necessary to make a proper bar chart?
- Modify the code by adding `.encode(tooltip=['Product', '2014'])`. How does this improve the interaction with the visualization?

### Different markers

You can see the different styles of point markers and the options for them here [altair mark documentation](https://altair-viz.github.io/user_guide/marks.html). Above we also changed the colour of the marker - this is something can specify with a name of a colour (as we did - range of options available), or with a hex code for the colour of the form `color='#CA02D9'`. A good resource for picking colours and finding this hex format to specify them is [Adobe's color tool](https://color.adobe.com/create/color-wheel/) it's really helpful for picking matching colors too.

### Adding plots on same axes

Here's an example of adding plots of two data sets on the same axes using different colours picked from that website.

In [15]:
# This snippet creates two separate scatter plots with triangle markers using the fish DataFrame, one for the
# year 2014 (a) and another for 2015 (b). The mark_point() function specifies the shape and color for each plot.
# The plots are then combined using the + operator, layering them on top of each other to compare the values
# for 2014 and 2015.
a = alt.Chart(fish).mark_point(size=80, shape='triangle', color='#CA02D9').encode(
    x='Product',
    y='2014',
)
b = alt.Chart(fish).mark_point(size=80, shape='triangle', color='#5FD902').encode(
    x='Product',
    y='2015',
)
# Combining these two figures together
a + b

alt.LayerChart(...)

Another example of multiple items added together to make a plot, this time done done a slightly different way by starting the 'Chart' and noting which data is to be used, but then adding the marks encoding the data in a separate line.

In [20]:
# This code creates a layered chart using the fish DataFrame. It first encodes the 'Product' column to the x-axis
# and the '2014' column to the y-axis. Then, it layers different marks: a green line, red circles, and a rule.
# This combination provides a comprehensive view of the data for 2014.
plt = alt.Chart(fish).encode(
    x='Product',
    y='2014'
)

# Adds a green line connecting data points, illustrating trends or changes across 'Product' categories.
# Overlays red circles on each data point.
# By default, mark_rule() creates vertical or horizontal lines spanning the axis
plt.mark_line(color='green') + plt.mark_circle(size=100, color='red') + plt.mark_rule()

alt.LayerChart(...)

**Reflecting on the data viz**

- Do you think we really need this linkage on the data points ? This last plot is not reasonable, and as we noted earlier linking up the data along the x axis doesn't make much sense for this data. 
- What do you find when you remove that coding part `plt.mark_line(color='green')` in the last line ?

On that topic, this data would clearly make a good bar chart, and that would be another obvious style of visualisation to use here and would emphasise that the x axis consists of categorical data. Here is some code to make a bar chart:

In [21]:
# This code creates a barchart. It first encodes the 'Product' column to the x-axis
# and the '2014' column to the y-axis. Then, it colours the bars with lightblue
alt.Chart(fish).mark_bar(color='lightblue').encode(
    x='Product',
    y='2014',
)

alt.Chart(...)

In [22]:
# This code creates two separate bar charts using the fish DataFrame. The first chart, 'left',
# is a bar chart that maps the 'Product' column to the x-axis and the '2014' column to the y-axis,
# with bars colored in light blue. The second chart, 'right', is similar but maps the '2017' column
# to the y-axis instead. The alt.hconcat(left, right) function horizontally concatenates these two
# charts, placing them side by side for easy comparison of product values between 2014 and 2017.
left = alt.Chart(fish).mark_bar(color='lightblue').encode(
    x='Product',
    y='2014',
)
right = alt.Chart(fish).mark_bar(color='lightblue').encode(
    x='Product',
    y='2017',
)
# It's also possible to stack the visualisations vertically rather than horizontally with alt.vconcat()
alt.hconcat(left, right)

alt.HConcatChart(...)

We add one more thing here too, when we specify the data for the x and y parts of the plot we add a colon and a letter (e.g. `Product:N`). This is the way we can let Altair know what sort of data is contained in that column, there are five main data types:

| Data Type     | Shorthand Code | Description                          |
|---------------|--------------|--------------------------------------|
| **quantitative** | 'Q'          | A continuous real-valued quantity   |
| **ordinal**      | 'O'          | A discrete ordered quantity         |
| **nominal**      | 'N'          | A discrete unordered category       |
| **temporal**     | 'T'          | A time or date value                |
| **geojson**      | 'G'          | A geographic shape                  |


For the moment we will mostly be focussed on the first three of these types. 

(More details here [Altair docs](https://altair-viz.github.io/user_guide/encodings/index.html#encoding-data-types)).

For these last plots we will change the axes labels as well to be some text we choose rather than just the column names from the data.

In [23]:
# The first chart, 'top', is a bar chart that maps the 'Product' column to the x-axis and the '2014' column to the y-axis.
# The x-axis is labeled as 'Product imported', and the y-axis is labeled as 'Value imported to US in 2014 ($)'.
# The bars are colored in light blue.  
top = alt.Chart(fish).mark_bar(color='lightblue').encode(
    x=alt.X('Product:N', title='Product imported'),
    y=alt.Y('2014:Q', title='Value imported to US in 2014 ($)')
)
# The second chart, 'bot', is similar but maps the '2017' column
# to the y-axis, with the y-axis labeled as 'Value imported to US in 2017 ($)'.
bot = alt.Chart(fish).mark_bar(color='lightblue').encode(
    x=alt.X('Product:N', title='Product imported'),
    y=alt.Y('2017:Q', title='Value imported to US in 2017 ($)')
)

# The alt.vconcat(top, bot) function vertically concatenates these two charts, stacking them on top of each other for easy comparison
# of product values between 2014 and 2017.
alt.vconcat(top, bot)

alt.VConcatChart(...)

## Stacking up

Let's try and stack up even more of the data in one plot - there are two things going on in this data, 'Product' and 'year', when we combine everything on one plot we need to ask - which one is more important? 

- Look at the data The years are not collectively labelled, so not grouped in the spreadsheet (see the 'head' of the spreadsheet with the data in below), just each column labelled one by one '2014', '2015', etc. 
- So we need to group them to be able to refer to them collectively and start making plots using all of them - that needs a transformation of the data, and the one we want here Altair calls a 'fold', we want to fold the years into one item called 'Years'. 

**Here is how we do that.** 

Note we keep a collective item called 'Years' and 'Year' refers to the data within each of those columns separately. We will keep here the 'Product' as being the key grouping, so we primarily group the data together by 'Product' (column in the way this is structured below) and then plot the 'Years' as the x axis of each plot with each individual 'Year' data giving a value which is plotted on the y axis. We'll also choose to colour things by the 'Product' groupings.

In [28]:
# The transform_fold() function is used to transform the data by folding the specified columns 
# ['2014', '2015', '2016', '2017', '2018'] into two new columns named 'Years' and 'Year'. 
# This transformation allows the data to be visualized
# in a long-form format suitable for faceted plots. 

# The mark_bar() function specifies that the chart should be a bar plot. 
# The encode() method maps 'Years' to the x-axis, 'Year' to the y-axis, and
# 'Product' to both the color and the column facets. 

# This results in a faceted bar chart where each
# column represents a different product, and each bar within those columns represents the value for
# a specific year, colored by product.
alt.Chart(fish).transform_fold(['2014', '2015', '2016', '2017', '2018'], as_=['Years', 'Year']).mark_bar().encode(
    x='Years:N',
    y='Year:Q',
    color='Product:N',
    # column='Product:N'
)

alt.Chart(...)

In [29]:
# For the relabelling the second label can be "value" 
alt.Chart(fish).transform_fold(['2014', '2015', '2016', '2017', '2018'], as_=['Years', 'Value']).mark_bar().encode(
    x='Years:N',
    y='Value:Q',
    color='Product:N',
    # column='Product:N' # If we open this it serves like faceting in plotnine roughly 
)

alt.Chart(...)

That's a lot of plots, so harder to see as a piece together (you probably have scroll bars to scroll around the visualisation). 

We could just have well have decided that actually the Years were the better grouping and have used 'Product' as the x axis. Here's how that would look (note the fold transformation is just the same as it is really just changing our view of the spreadsheet the same way to group the 'Years' together):

In [30]:
# It folds the years 2014-2018 into 'Years' and 'Year' columns, creating a bar chart for each year. The x-axis represents 'Product',
# the y-axis represents 'Year' values, bars are colored by 'Years', and each facet represents a year.
alt.Chart(fish).transform_fold(['2014', '2015', '2016', '2017', '2018'], as_=['Years', 'Year']).mark_bar().encode(
    x='Product:N',
    y='Year:Q',
    color='Years:N',
    column='Years:N'
)

alt.Chart(...)

**Again, large because of all the data so you may need to scroll around to see the whole visualisation.** 

- This is the sort of exploration of different facets and ways of folding the data that it is really common to do in the exploration phase of looking at a data set. 
- These visualisations bring different things into proximity and help highlight different relationships in the data. During data exploration, when you get a new data set and try to make sense of it, this can be really helpful.

One last thing for these sorts of combined plots, what about just putting the columns right on top of each other? 

Note: `transform_fold()` component is serving to convert wide-form data to long-form data directly without any preprocessing (see Long-form vs. Wide-form Data for more information). Fold transforms are the opposite of the Pivot.

In [31]:
# Create a bar chart using the fish DataFrame, transforming the data for multiple years.
alt.Chart(fish).transform_fold(
    # Fold the specified years into two new columns: 'Years' and 'Year'.
    ['2014', '2015', '2016', '2017', '2018'], as_=['Years', 'Year']).mark_bar(
    # Set the opacity of the bars to 0.4 for a semi-transparent effect.
    opacity=0.3).encode(
    # Encode the x-axis with the 'Product' field as nominal data.
    alt.X('Product:N'),
    # Encode the y-axis with the 'Year' field as quantitative data, with no stacking.
    alt.Y('Year:Q', stack=None),
    # Encode the color of the bars based on the 'Years' field as nominal data.
    color='Years:N'
)

alt.Chart(...)

- Here you can see we have tried this two different ways. 
- First by overlaying the bars always starting at the same place, but making them slightly transluscent. 
- Second by stacking each bar on top of the ones that came before. 

Both of these sorts of plots have their uses - but for me neither is very satisfying, they both make it pretty hard to compare things that we might like to compare. What else we can do for an easy comparison with the functions from Altair do you think ? Feel free to explore bar chart related examples from here: https://altair-viz.github.io/gallery/index.html

## Interactive elements in Altair

This part of the notebook will focus on adding elements which make visualisations in Altair interactive. We will start by revisiting one of the previous visualisations on fishimport data set 

### Basic scroll and zoom interactivity

Firstly let's go back to the very first data set we looked at for visualisation purposes 
- it concerned data about US fish imports over recent years and come from the US government [here](https://www.ers.usda.gov/data-products/aquaculture-data.aspx). 
- We can read it in and print out the first few lines to remind ourselves what it contains:

In [2]:
import pandas as pd
import altair as alt

fish = pd.read_excel('fishimportdata.xlsx')
fish.head()

,Product,2014,2015,2016,2017,2018
0,"Trout, fresh and frozen",95011.936,104791.429,120977.955,135236.725,164695.746
1,"Atlantic salmon, fresh",568901.674,658831.066,842603.917,948877.175,1035924.073
2,"Pacific salmon, fresh",111540.545,69978.873,80010.180,70733.165,90324.372
3,"Atlantic salmon, frozen",21457.836,16356.453,24230.787,22492.341,20197.169
4,"Pacific salmon, frozen",224334.704,238962.677,246204.469,302340.719,360673.107

The very simplest interactivity we can add is simply to allow scrolling and zooming on the axes we create. 

Here's how that looks for a bar chart visualisation of one of the years of data - we add `.interactive()` to our chart to permit it:

- This might be practically useful in that if we haven't quite decided on an appropriate scale we can use this to scroll (only up and down here) and zoom (use your scroll wheel) to get it how we would like it to look. 

- There is a limit here when the axis in question is nominal or ordinal in that the scroll won't let us move that axis.

In [32]:
# Create a chart using the fish data as bar chart for color: color='lightblue'
alt.Chart(fish).mark_bar().encode(
    x='Product:N', # Using product as a nominal type
    y='2014:Q', # using 2014 column as quantitative
).interactive() # Adding the .interactive property to allow scrolling and zooming

alt.Chart(...)

**Try the followings and reflect**

- What if you drop `.interactive()` in your display ?

### Combining two types on an interactive setting

Let's look at another example of two axes which are both quantitative so that we are allowed scrolling in both directions. 

- Here is a visualisation of the numbers for 2015 imports plotted against the numbers for 2014 imports. This sort of visualisation can help us to see quickly which imports have gone up or down year-on-year. 
- To help with that we can add on top a straightline that looks like 'y=x', if a point from our data lies exactly on that line then imports remain the same in both years, below and they have decreased, above and they have increased.

In [33]:
a = alt.Chart(fish).mark_circle(color='blue').encode(
        x=alt.X('2014:Q', title='2014 imports'),  # Map the '2014' column (quantitative data) to the x-axis with a custom title.
        y=alt.Y('2015:Q', title='2015 imports')   # Map the '2015' column (quantitative data) to the y-axis with a custom title.
    ).interactive()  # Enable interactive features such as zooming and panning.

a

alt.Chart(...)

In [34]:
# Create a scatter plot using the 'fish' DataFrame.
a = alt.Chart(fish).mark_circle(color='blue').encode(
        x=alt.X('2014:Q', title='2014 imports'),  # Map the '2014' column (quantitative data) to the x-axis with a custom title.
        y=alt.Y('2015:Q', title='2015 imports')   # Map the '2015' column (quantitative data) to the y-axis with a custom title.
    ).interactive()  # Enable interactive features such as zooming and panning.

# Create a DataFrame for the reference red line.
# This DataFrame contains two points: (0, 0) and (5,000,000, 5,000,000) to form a diagonal line.
linedata = pd.DataFrame({
    'x': [0, 5000000],  # x-coordinates for the line.
    'y': [0, 5000000]   # y-coordinates for the line.
})

# Create a line chart using the 'linedata' DataFrame.
b = alt.Chart(linedata).mark_line(color='red').encode(
        x=alt.X('x:Q', title=''),  # Map the 'x' field (quantitative data) to the x-axis without a label.
        y=alt.Y('y:Q', title='')   # Map the 'y' field (quantitative data) to the y-axis without a label.
    )

# Overlay the red line chart 'b' on top of the scatter plot 'a'.
# The '+' operator is used in Altair to combine charts.
b + a

alt.LayerChart(...)

- Now the interaction is genuinely useful on this visualisation, since if we view the chart as a whole there is one outlier on the right-top corner

- We could make a second zoomed version that was also static, but by allowing scrolling and zooming it is just simpler to explore the data as a whole and get a better sense of it.

**REMARK:** Note also in this last example you can see an ad hoc definition of a dataframe as well `linedata = pd.DataFrame({'x': [0,5000000], 'y': [0,5000000]})`, this is the first time we have used this. Broadly the structure is quite straightforward to read, this defines a dataframe with two columns 'x' and 'y' each with two data values in the. 

- The main difficulty is just that care is needed to make sure the different brackets pair up correctly. 
- Here we are using this to provide data to be able to draw the straight line, and so only need two data points to join together. 
- Indeed this ad hoc dataframe definition is good where you quickly want to define a few points for a line or curve, any more than that and it becomes easier to enter the data into a spreadsheet and read it in more properly.

### Hover interactions with `tooltip`

We have already seen another reasonably basic interaction that Altair can overlay on our chart, namely the popup of data values when we hover the mouse over an data mark on the chart. 

- This hover interaction is called a `tooltip` in Altair, and we used it to get data value on the pie chart created in the last notebook, Set 2. 
- To show a second example let's use it here to label the data values in the last chart since currently there is nothing which notes which type of product is imported for each value, so we could add a tooltip to encode that:

In [35]:
# Create a chart using the fish data as bar chart
a = alt.Chart(fish).mark_circle(color='blue').encode(
    x=alt.X('2014:Q',title='2014 imports'), # Map the '2014' column (quantitative data) to the x-axis with a custom title.
    y=alt.Y('2015:Q',title='2015 imports'), # Map the '2015' column (quantitative data) to the y-axis with a custom title.
    tooltip=['Product','2014','2015'] # tooltip property allows hovering over a point to see details
).interactive()

a

alt.Chart(...)

Adding the tooltip is then as simple as listing the fields we want to be included in the popup caption when the mouse hovers over the data point in the chart. 
In the previous notebook we also saw that the tooltip fields could include fields calculated as part of a `transform` function in Altair that aggegates data.

**Try the followings and reflect**

- What if you dropped `.interactive()` in your display ? 
- What is the upper-right corner observation details when you move your curser there ?

## Dropdown and radio buttons for selection

Next we can reuse the same data again to look at interacting with a chart by selecting items from a dropdown list or using radio buttons. 

Recall we used before a fold transform so we could fold together the years in our dataset into one field, and this also enables us to refer to the dates as elements within that field - here was the code we used to then stack up the bars for each year in one chart

In [36]:
alt.Chart(fish).transform_fold(['2014','2015','2016','2017','2018'], as_=['Years','Value']
).mark_bar().encode(
    x=alt.X('Product:N'), 
    y=alt.Y('Value:Q',stack=True),
    color='Years:N', 
    tooltip = ["Product"]
)

alt.Chart(...)

Here we can get away with using a second transform (two don't always work), and we can use a filter transform to select only the year '2014' from the field we created 'Years'. Here's how that would look:

In [37]:
alt.Chart(fish).transform_fold(['2014','2015','2016','2017','2018'], as_=['Years','Year']
).mark_bar().encode(
    x=alt.X('Product:N'),
    y=alt.Y('Year:Q',stack=True),
    color='Years:N'
).transform_filter(
    alt.FieldEqualPredicate(field='Years', equal='2018')
)

alt.Chart(...)

### Dropdown box

- This gives us a template for then choosing which year gets shown by using a dropdown list of the years and allowing interaction to choose one from the list which is then shown in the visualisation. 

- To do that we need to define a dropdown set of options, and a 'binding' to bind those options to a selection from a particular data field. 
- To make it all work together we then need to add the function `.add_params()` to add our binding to the chart. 

Here we also now let the transform filter use the selection we pick, so that the dropdown has the effect we want of picking out the year that gets drawn in the visualisation:

In [38]:
# Define a dropdown menu binding with year options.
year_dropdown = alt.binding_select(options=['2014', '2015', '2016', '2017', '2018'])

# Create a selection object for a single item, bound to the dropdown menu.
year_select = alt.selection_single(
    fields=['Years'],    # Selection based on the 'Years' field.
    bind=year_dropdown,  # Bind the selection to the dropdown options.
    name='Select'        # Name the selection 'Select'.
)

# Create a bar chart using the 'fish' DataFrame.
chart = alt.Chart(fish).transform_fold(
    ['2014', '2015', '2016', '2017', '2018'],  # Transform data from wide to long format.
    as_=['Years', 'Value']  # Rename the transformed columns to 'Years' and 'Year'.
).mark_bar().encode(
    x=alt.X('Product:N'),  # Encode the x-axis with categorical 'Product' data.
    y=alt.Y('Value:Q')      # Encode the y-axis with quantitative 'Year' data.
).add_params(
    year_select  # Add the dropdown parameter to the chart.
).transform_filter(
    year_select  # Filter the data based on the selected year from the dropdown.
)

# Display the chart.
chart

/opt/conda/lib/python3.9/site-packages/altair/utils/deprecation.py:65: AltairDeprecationWarning: 'selection_single' is deprecated.  Use 'selection_point'
  warnings.warn(message, AltairDeprecationWarning, stacklevel=1)

alt.Chart(...)

- Hopefully you can see how this pieces together. the `alt.binding_select()` part lists the options we want in the dropdown list, and we pass them in as a list like this `options=['2014','2015','2016','2017','2018']`. 
- Note here our years are listed as strings (text) with '' around each year, not as numbers - for a different dataset they might be listed as numbers instead, but this works for this data.

Then the binding part links the options to a field within the data we want to visualise. Here `alt.selection_single()` makes a single selection from the dropdown link to something in the chart. Then `fields=['Years']` details which field is being connected to the options, `bind=year_dropdown` connects the dropdown option list here, and `name='Select'` is the label that gets used next to the dropdown box. If you don't use a name then a default piece of text appears there and looks even uglier (the text 'Years' part appears in the label next to the dropdown even when we specify the name). This 'name' part of the interactivity just looks a little messy in the way that Altair constructs it (although this element actually depends a bit on your browser, as different ones render the dropdown to look slightly different!).

### Radio buttons

Another way of selecting from a list is to use radio buttons (round selection buttons). 

- The possible benefit of radio buttons is that all the possible options are listed out as plainly visible rather than hidden in a dropdown list. 
- The code for doing this is really similar to before, we use the `alt.binding_radio()` function to make our radio button option list now. The example shows how to put this together, note it also includes an initialisation of the radio buttons (so one is selected by default initially) by specifying `value=[{'Years':'2014'}]`. 
- The form for that option is to put the field name and the initial option together into that format.

In [39]:
# Adding the radio button binding for the options of different years
year_radio = alt.binding_radio(options=['2014','2015','2016','2017','2018'])
# Create a selection with type=’single’ for the each field by using the above options for the Year field, 
# as the default is selected as 2014
year_select = alt.selection_single(fields=['Years'], 
                                   bind=year_radio, 
                                   name='Select', # Name the selection 'Select'.
                                   value=[{'Years':'2014'}])

# Transform data from wide to long format with transform_fold()
alt.Chart(fish).transform_fold(['2014','2015','2016','2017','2018'], as_=['Years','Year']
).mark_bar().encode(
    x=alt.X('Product:N'), # X axis for the product as nominal
    y=alt.Y('Year:Q'), # Y axis for the years but keeping quantitative information
    tooltip = ["Product"]
).add_selection(
    year_select # Add the radio buttons to the chart.
).transform_filter(
    year_select # Filter the data based on the selected year from the dropdown.
)

/opt/conda/lib/python3.9/site-packages/altair/utils/deprecation.py:65: AltairDeprecationWarning: 'add_selection' is deprecated. Use 'add_params' instead.
  warnings.warn(message, AltairDeprecationWarning, stacklevel=1)

alt.Chart(...)

With an understanding of the parameter types and conditions, you can now bind parameters to chart elements (e.g. legends) and widgets (e.g. drop-downs and sliders). This is done using the bind option inside param and selection.

There are some other types of selections such as 

- Interval Selection: `alt.selection_interval()`
- Single Selection: `alt.selection_single()`
- Multi Selection: `alt.selection_multi()`

###  Selection Example for Interval with `alt.selection_interval`

As an example of a selection, let’s add an interval selection to a chart.

- To add selection behavior to a chart, we create the selection object and use the add_selection method:
- This adds an interaction to the plot that lets us select points on the plot; perhaps the most common use of a selection is to highlight points by conditioning their color on the result of the selection.

In [40]:
interval = alt.selection_interval()

# Create a bar chart with transformed data for multiple years
alt.Chart(fish).transform_fold(
    ['2014', '2015', '2016', '2017', '2018'],  # Convert wide data into long format
    as_=['Years', 'Value']  # Rename columns: 'Years' for labels, 'Value' for values
).mark_bar(color='lightblue'  # Set bar color
).encode(
    x=alt.X('Product:N'),  # Categorical x-axis for products
    y=alt.Y('Value:Q'),  # Quantitative y-axis for yearly values
).add_selection(
    interval  # Add the interval selection to the chart
)

alt.Chart(...)

### Legend interaction with `alt.selection_multi()`

Another nice interaction that Altair offers is to be able to select one of the items in the legend and then do something with it. 

- Here's how that looks, we don't have to specify an initial options list as we don't need to create a new element, the options are just the legend. 
- We do need the binding part though now specified as `alt.selection_multi()`, and with the option `bind='legend'` specified to connect to the legend as the means for selection.

In [41]:
# Create a multi-selection for years, linked to the legend
year_select = alt.selection_multi(fields=['Years'], bind='legend')

# Create a line chart with transformed data for multiple years
alt.Chart(fish).transform_fold(
    ['2014', '2015', '2016', '2017', '2018'],  # Convert wide data into long format
    as_=['Years', 'Value']  # Rename columns: 'Years' for labels, 'Value' for values
).encode(
    x=alt.X('Product:N'),  # Categorical x-axis for products
    y=alt.Y('Value:Q', title='Imports $'),  # Quantitative y-axis with custom title
    color='Years:N'  # Different colors for each year
).mark_line(point=True  # Add points to the line plot
).add_params(year_select)  # Add the selection to the chart

/opt/conda/lib/python3.9/site-packages/altair/utils/deprecation.py:65: AltairDeprecationWarning: 'selection_multi' is deprecated.  Use 'selection_point'
  warnings.warn(message, AltairDeprecationWarning, stacklevel=1)

alt.Chart(...)

- Well that's worked, but when we make a selection it doesn't do anything to the chart as we haven't used the selection we've made anywhere to change anything about the plot. 
- To do something let's make the year we select highlighted by making it coloured and making the other lines a bit more transparent. 
- We can control that by another option `opacity` which we haven't yet used and an `alt.condition()` function which we also haven't seen yet. 
- Opacity just makes a line more or less opaque by supplying a number between 0 (invisible) and 1 (normally coloured). 

Here, the `alt.condition()` function allows us to specify something to be dependent on a condition. We need to supply three things to this;

- (1) a condition, 
- (2) a value if the condition is true, 
- (3) and a value is the condition is false. 

Here our condition is whether the year is selected in the legend coming from our binding `year_select`, the values we specify as numbers using `alt.value()` to make sure the value is properly encoded for altair to grasp it. The value if true is `alt.value(1)` so opacity 1, and if false `alt.value(0.2)` opacity 0.2.

Here's how that looks:

In [42]:
# Create a multi-selection for years, linked to the legend
year_select = alt.selection_multi(fields=['Years'], bind='legend')

# Create a line chart with transformed data for multiple years
alt.Chart(fish).transform_fold(['2014','2015','2016','2017','2018'], as_=['Years','Year']).encode(
    x=alt.X('Product:N'), # Categorical x-axis for products
    y=alt.Y('Year:Q',title='Imports $'), # Quantitative y-axis with custom title
    color='Years:N', # Different colors for each year
    opacity=alt.condition(year_select, alt.value(1), alt.value(0.2))
).mark_line(point=True).add_params(year_select)

alt.Chart(...)

- This effectively works through and checks if any selection is made. When a selection is made the selection is true for the selected year - meaning that is marked in full colour, and false for all the other lines - meaning they are marked with opacity 0.2.

- This sort of legend interation can be useful for making sure that lines can be pulled out and individually highlighted, particularly appropriate where lines overlap such as in the above visualisation.

### Sliders for selection

One other method for selection is a slider. This is a similar type of selector as the radio buttons above, but this only works for selecting a number - so a quantitative field.

- We can introduce this using our UK wood import data, in fact we will use a long form of the previous UK wood import data set which was presented in wide form in the exercises previously. 
- For the difference between long and wide forms of data have a look at the following link in the Altair documentation
https://altair-viz.github.io/user_guide/data.html#long-form-vs-wide-form-data.
- In short, both ways of formatting the data present the same things but are easier to index in one form or the other to produce a particular visualisation we might want.

In [43]:
# Importing the data set and looking at the first few observations
wood = pd.read_excel('UK_wood_imports2.xlsx')
wood.head()

   Year      Type  Amount
0  2013  Sawnwood    5488
1  2014  Sawnwood    6425
2  2015  Sawnwood    6323
3  2016  Sawnwood    6646
4  2017  Sawnwood    7580

- The related code snippet for adding a slider looks really quite similar to the previous selection methods so we can work through it here in one example. 
- We'll add a slider to select the year, and make a bar chart from the data for that year.

The main change here is in the selection tool, to obtain a slider we use `alt.binding_range()` and then need to specify a minimum and maximum value for our slider to index, and also the step each time we move the slider. Here we choose to go from 2013 to 2017 in steps of 1 to cover all the possible years.

- The binding looks much as before, and here we use our selection as the input to a filter transform bound to the field 'Year' in order to filter out only the year we select in our data.

In [62]:
year_slider = alt.binding_range(min=2013, max=2017, step=1)
slider_selection = alt.selection_single(bind=year_slider, fields=['Year'], name="Select",value=[{'Year':2013}])

alt.Chart(wood).mark_bar(color='lightblue').encode(
    x=alt.X('Type:N'), # Categorical x-axis for type
    y=alt.Y('Amount:Q') # Quantitative y-axis for amount
).add_params(
    slider_selection # adding the binned slider selection over years, starting with 2015 as default
).transform_filter(
    slider_selection # This is necessary to put the slider into action!
)

alt.Chart(...)

- The main drawback for use of a slider is that they are only permitted in altair for numbers, and in practice we have seen years often are given as strings eg. '2013' rather than 2013, which wouldn't allow us to use one.

## Optional reading: Selection brushes and linked charts

Another important interactive element available in Altair is linked selections across multiple charts. That is a selection tool (usually called a brush or interval tool) which allows the selection of some data points in a chart using the mouse, which then changes a second linked chart.

As a general strategy, good to explore certain use cases to detect how these examples created and identify which data set is used there in which way. Afterwards, it might be possible to adapt that example to your data set

- The 'interactive' section of the gallery in the Altair documentation https://altair-viz.github.io/gallery/index.html#interactive-charts has a good few examples of this type of interaction for your possible project related explorations.

## Open-Ended Exercises

Here are some more exercises around interactive charts for you to try out and reflect on after covering the above examples. Again any of these are suitable visualisations to add into your portfolio.

1) Try out a visualisation of the different products in the year 2017 using a bar chart, for the data set `fishimportdata.xlsx`. 
- How would you get started? 
- Can you change the colour and the text (title) used to label each axis?

2) Read in the dataset `'anscombe.xlsx'` which contains the various data used to construct Anscombe's quartet that was mentioned in the lecture (see [here](https://en.wikipedia.org/wiki/Anscombe%27s_quartet) also). 

Try making some visualisations of this data using the pairs of x,y coordinates you can find across the columns of the excel file. Can you make them as separate scatter plots, put them side by side, or above each other, and finally style them appropriately (choosing colour, symbol, and titling the axes).

3) From the UK dataset [here](https://data.gov.uk/dataset/34758844-5e83-450a-81c9-7a0e2ca0d6b1/uk-wood-production-and-trade-2017-provisional-figures) we can get information about UK wood imports. This is pre-processed into a simpler form in the spreadsheet `'UK_wood_imports.xlsx'`. Using the ideas you have seen above make some visualisations of this dataset (note the numbers are in thousands of cubic metres).

4) The penguins dataset contained in `penguins.csv` is a nice set of data for different visualisations that contains measurements of various characteristics of some small penguin species (see [here](https://allisonhorst.github.io/palmerpenguins/) for some details about it and some visualisation ideas). 

- Try making some interactive visualisations of this data.   
- You can mimick the above examples to start with and customize further step by step.

5) The files `county-income.xlsx` and `county-medianhouseprice.xlsx` both come from the [ONS](https://www.ons.gov.uk/peoplepopulationandcommunity/housing/datasets/ratioofhousepricetoworkplacebasedearningslowerquartileandmedian) (Office for National Statistics). 

- They contain data on average incomes and average house prices over time for each English county. 
- They have a very similar format to the marine conservation dataset discussed above. 
- Try making some interactive visualisations of them, maybe try linking two charts (you might want to make a new version of the spreadsheet with an 'Average' column to average across all the years).

## Further Exercising 

- https://altair-viz.github.io/altair-tutorial/README.html can be a good supplementary website to search for certain type of visualizations to inspire from them. 

- You can try to create new versions of the Fringe data set example from the python script `From_Scratch` by improving step by step. 

- Try open ended questions and let us know your journey! Besides, min exercises can be used for later purposes if you create an answer for one specific data, you can adapt your code to tailor for another data set. 

These are some specific case study style altair examples that you can benefit from: 

- [Data Visualization: A Walkthrough in Python with Altair](https://huppenkothen.org/data-visualization-tutorial/13-walkthrough-altair/index.html)

- [Altair in Python Tutorial: Data Visualizations](https://www.datacamp.com/tutorial/altair-in-python)